# Generated by Django 4.1 on 2022-10-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('status_type', models.IntegerField(verbose_name='状态类型')),
                ('start_time', models.DateTimeField(max_length=50, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(max_length=50, verbose_name='结束时间')),
            ],
        ),
    ]
