# Generated by Django 4.1 on 2022-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emoji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='end_time',
            field=models.DateTimeField(max_length=50, null=True, verbose_name='结束时间'),
        ),
    ]
