# Generated by Django 4.1 on 2022-10-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.BinaryField(verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('wx_openid', models.CharField(max_length=50, verbose_name='微信开放ID')),
            ],
        ),
    ]
