# Generated by Django 4.1 on 2022-10-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.BinaryField(null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='wx_openid',
            field=models.CharField(max_length=50, null=True, verbose_name='微信开放ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.BinaryField(null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=50, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=50, null=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.CharField(max_length=50, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wx_openid',
            field=models.CharField(max_length=50, null=True, verbose_name='微信开放ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.BinaryField(null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='wx_openid',
            field=models.CharField(max_length=50, null=True, verbose_name='微信开放ID'),
        ),
    ]
