# Generated by Django 4.1 on 2022-10-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_admin_age_alter_admin_gender_alter_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.IntegerField(null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.IntegerField(null=True, verbose_name='性别'),
        ),
    ]
