# Generated by Django 4.1 on 2022-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_admin_gender_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='admin',
            name='avatar',
            field=models.CharField(max_length=100, null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.CharField(max_length=100, null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.CharField(max_length=100, null=True, verbose_name='头像'),
        ),
    ]
