# Generated by Django 4.1 on 2022-10-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户名')),
                ('user_avatar', models.CharField(max_length=100, verbose_name='用户头像')),
                ('cont', models.CharField(max_length=1000, verbose_name='评论内容')),
                ('comment_type', models.CharField(max_length=50, null=True, verbose_name='评论类型')),
                ('time', models.CharField(max_length=50, null=True, verbose_name='评论时间')),
                ('is_delete', models.IntegerField(null=True, verbose_name='是否删除')),
            ],
        ),
    ]
