# Generated by Django 4.1 on 2022-10-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='nick_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_type',
            field=models.CharField(default='student', max_length=50, verbose_name='用户类型'),
            preserve_default=False,
        ),
    ]
