# Generated by Django 4.1 on 2022-10-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_alter_comment_nick_name_alter_comment_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='toxic_type',
            field=models.IntegerField(null=True, verbose_name='评论类型'),
        ),
    ]
