# Generated by Django 4.1 on 2022-10-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_comment_toxic_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
    ]
